/**
 * tdt4240-diving-duck-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.User

/**
 * 
 * @param id 
 * @param scoreXPos 
 * @param userId 
 * @param user 
 */
data class Score (

    val id: kotlin.Int,
    val scoreXPos: kotlin.Int? = null,
    val userId: kotlin.Int? = null,
    val user: User? = null
) {
}