/**
 * tdt4240-diving-duck-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ScoreResponse

/**
 * 
 * @param id 
 * @param userName 
 * @param scores 
 */
data class UserResponse (

    val id: kotlin.Int? = null,
    val userName: kotlin.String? = null,
    val scores: kotlin.Array<ScoreResponse>? = null
) {
}