/**
 * tdt4240-diving-duck-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.divingduck.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param scoreXPos 
 * @param userId 
 */

data class ScoreDTO (

    @Json(name = "scoreXPos")
    val scoreXPos: kotlin.Int,

    @Json(name = "userId")
    val userId: kotlin.Int? = null

)

