/**
 * tdt4240-diving-duck-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.divingduck.client.models

import com.divingduck.client.models.Score

import com.squareup.moshi.Json

/**
 * 
 *
 * @param userName 
 * @param scores 
 */

data class UserDTO (

    @Json(name = "userName")
    val userName: kotlin.String? = null,

    @Json(name = "scores")
    val scores: kotlin.collections.List<Score>? = null

)

